learning_templates/basic_app/urls.py
from django.urls import path
from basic_app import views

app_name='basic_app'

urlpatterns= [
  path('other/',views.other,name='other'),
  path('relative/',views.relative_url_templates,name='relative_url_templates'),

]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views

urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('basic_app/',include('basic_app.urls')),
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dic = {'text':'Hello world','number':100}
    return render(request,'basic_app/index.html',context=context_dic)

def other(request):
     return render(request,'basic_app/other.html')

def relative_url_templates(request):
    return render(request,'basic_app/relative_url_templates.html')

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" />
  </head>
  <body>
    
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'index' %}">BRAND</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="{% url 'admin:index'  %}">Admin<span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="{% url 'basic_app:other'  %}">Other</a>
<a class="nav-item nav-link" href="{% url 'basic_app:relative_url_templates'  %}">Relative</a>

    </div>
  </div>
</nav>
      <div class="container">
       {% block body_block %}
       <!--Anything outside of this will be inherited if you extend! -->
       {% endblock %}
        </div>

  </body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block %}

<h1>Welcome to Index</h1>

    <a href="{% url 'basic_app:other'  %}">THE OTHER PAGE<br /></a>
    <a href="{% url 'basic_app:relative_url_templates'  %}">THE RELATIVE PAGE<br /></a>
    <a href="{% url 'admin:index'  %}">ADMIN</a>
    <br />
  <h1> {{ text|cut:'Hello' }}</h1>
  <h1> {{ number|add:"20" }}</h1>
{% endblock %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block %}

    <h1>Welcome to others</h1>
    <h2>Example of template inheritance</h2>
    <a href="{% url 'index' %}">INDEX</a>
{% endblock %}

learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block %}

      <h1>Welcome to relative URL</h1>
    <h2>Example of template inheritance</h2>
    <a href="{% url 'index' %}">INDEX</a>
{% endblock %}